
# Image repo and tag to pull the image from
image:
  repository: au06/demo-app
  tag: 0.0.1

# Name for the service account configured with Vault k8s Auth  Mechanism
serviceAccountName: vault-demo

# Namespace to host this:
namespace: demo

# Name for the configmap to load the secrets-path
configMapName: variables-path

# Path where the vault injector agent will populate the secrets
secret_path: "/vault/secrets/config.env"

# Annotation neccessary to enable Vault Injector Sidecar
vault_annotations:
  vault.hashicorp.com/agent-inject: 'true'
  vault.hashicorp.com/role: 'demo-app'
  vault.hashicorp.com/agent-pre-populate-only: 'true'
  vault.hashicorp.com/agent-inject-secret-config.env: 'internal/data/database/config'
  vault.hashicorp.com/agent-inject-template-config.env: |
    {{- with secret "internal/data/database/config" -}}
    USERNAME={{ .Data.data.username }}
    PASSWORD={{ .Data.data.password }}
    {{- end }}
